sudo: required
services:
  - docker

before_install:
  - docker build -t emirelesg/docker-client -f ./client/Dockerfile.dev ./client/

script:
  - docker run -e CI=true emirelesg/docker-client yarn test -- --coverage